name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Tack för att du tog dig tid att lämna ett ärende!'
        pr-message: 'Ahww, din allra första pull request...  <3 '
